In [1]:
%pip install numpy
import numpy as np

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----------- ---------------------------- 3.4/12.3 MB 20.2 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.3 MB 17.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 17.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 12.1 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
numeri_primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])

maggiori_10 = numeri_primi[numeri_primi>10]
primi_pari = numeri_primi[numeri_primi%2 == 0]

print(numeri_primi)
print(maggiori_10)
print(primi_pari)

[ 2  3  5  7 11 13 17 19]
[11 13 17 19]
[2]


In [16]:
arr = np.arange(1, 13).reshape(4,3)
print(arr)
a = arr[[1,3],:]
c = arr[2,:]
print(f"array a: {a}")
print(f"array c: {c}")

res = a/c
print(f"risultato: {res}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array a: [[ 4  5  6]
 [10 11 12]]
array c: [7 8 9]
risultato: [[0.57142857 0.625      0.66666667]
 [1.42857143 1.375      1.33333333]]


In [17]:
arr_random = np.random.rand(10,3)
dis = np.abs(arr_random - 0.5)
i_minimi = np.argmin(dis, axis=1)
vicini = arr_random[np.arange(10), i_minimi]
print(f"array random: {arr_random}")
print(f"array vicini a 0.5: {vicini}")


array random: [[0.99480445 0.02969861 0.63326085]
 [0.41902182 0.20576913 0.89817108]
 [0.84459398 0.26778012 0.47877182]
 [0.74294847 0.75253375 0.55660119]
 [0.23080505 0.18147326 0.08756659]
 [0.94098482 0.87886114 0.34418263]
 [0.38424443 0.47871041 0.93431189]
 [0.87440525 0.82630621 0.75401068]
 [0.67858796 0.98141273 0.55454636]
 [0.20017142 0.43121171 0.15208396]]
array vicini a 0.5: [0.63326085 0.41902182 0.47877182 0.55660119 0.23080505 0.34418263
 0.47871041 0.75401068 0.55454636 0.43121171]


In [18]:
freq = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

print("Frequenza Minima (Riposo):", freq.min())
print("Frequenza Massima (Esercizio):", freq.max())

esercizio_mask = freq > 120
print("Array Booleano Esercizio:", esercizio_mask)

percentuale = np.mean(esercizio_mask) * 100
print(f"Percentuale tempo esercizio: {percentuale:.2f}%")

Frequenza Minima (Riposo): 60
Frequenza Massima (Esercizio): 164
Array Booleano Esercizio: [False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
Percentuale tempo esercizio: 52.38%


In [19]:
stipendi = np.array([50000, 105250, 55000, 89000])
print("Costo totale iniziale:", stipendi.sum())


stipendi = np.array([50000, 105250, 55000, 89000], dtype=float)


stipendi[stipendi == 105250] *= 1.15
print("Nuovo stipendio CEO:", stipendi[1])


stipendi[stipendi == 50000] *= 1.20


stipendi[(stipendi != 121037.5) & (stipendi != 60000)] *= 1.10

print("Vettore stipendi finale:", stipendi)
print("Costo totale finale:", stipendi.sum())

Costo totale iniziale: 299250
Nuovo stipendio CEO: 121037.49999999999
Vettore stipendi finale: [ 60000.   133141.25  60500.    97900.  ]
Costo totale finale: 351541.25


In [21]:
#età,reddito,istruzione
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])

mask_istruzione = survey_matrix[:, 2] >= 12
intervistati_istruiti = survey_matrix[mask_istruzione]
print("Istruzione >= 12:\n", intervistati_istruiti)

redditi = survey_matrix[survey_matrix[:, 2] >= 12, 1]
print("Redditi selezionati:", redditi)

medio = survey_matrix[survey_matrix[:, 2] >= 12, 1].mean()
print(f"Reddito medio: {medio:.2f}")

Istruzione >= 12:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
Redditi selezionati: [52000 63000 58000]
Reddito medio: 57666.67


In [22]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55, 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100, 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79, 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70, 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99, 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96, 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83, 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999, 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78, 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90, 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68, 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83, 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74, 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85, 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80, 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70, 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92, 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98, 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92, 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72, 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68, 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83, 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67, 108, 58, 95, 106, 83, 79, 67, 59, 96, 90, 55, 55, 96, 109, 82, 55, 101, 58, 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59, 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69, 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99, 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

clean_ages = ages[ages != 999]

anziano = clean_ages.max()
print("Età del cittadino più anziano:", anziano)

Età del cittadino più anziano: 112


In [1]:
import numpy as np

lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

scelte = np.random.choice(lista_parole, size=5, replace=True)

storia = f"""In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {scelte[0]} che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il {scelte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "{scelte[2]}".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {scelte[3]}.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {scelte[4]}!" 
Ci fu grande gioia e celebrazione."""

print(storia)

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico NEMICO che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DIFFERENZA come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "NEMICO".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un APPLICAZIONE.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza AGENTE DI POLIZIA!" 
Ci fu grande gioia e celebrazione.
